### ISSUE TITLE
Incompatible with several popular plugins

### ISSUE THREAD

**Issue by leoniscsem** [MayamaTakeshi/redmine_rt#5] opened 2021-12-29 05:55 UTC
When having the plugin [mega_calendar](https://www.redmine.org/plugins/mega_calendar) installed at the same time, **redmine_rt** throws an error 500, when:
* opening a ticket
* creating a new issue and saving it (but not when creating a new issue and clicking "save and continue"

I know maintaining compatibility with each single other plugin is of course not your scope, but perhaps you would like to add this information on your plugin page at redmine.org.

**production.log**
```
Started GET "/issues/45" for <IP-ADDRESS> at 2021-12-29 13:33:53 +0800
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"45"}
  Current user: <USERNAME> (id=XYZ)
  Rendering plugins/redmine_rt/app/views/issues/show.html.erb within layouts/base
  Rendering plugins/mega_calendar/app/views/issues/show.html.erb
  Rendered issues/_action_menu.html.erb (2.9ms)
  Rendered plugins/redmine_agile/app/views/issues/_issue_story_points.html.erb (1.5ms)
  Rendered plugins/redmine_agile/app/views/issues/_agile_data_labels.html.erb (1.7ms)
  Rendered issue_relations/_form.html.erb (0.7ms)
  Rendered issues/_relations.html.erb (1.2ms)
  Rendered issues/_action_menu.html.erb (1.9ms)
  Rendered issues/_form_custom_fields.html.erb (0.1ms)
  Rendered plugins/mega_calendar/app/views/issues/_attributes.html.erb (21.4ms)
  Rendered plugins/redmine_agile/app/views/issues/_issue_story_points_form.html.erb (0.5ms)
  Rendered plugins/redmine_agile/app/views/issues/_agile_data_fields.html.erb (0.8ms)
  Rendered plugins/mega_calendar/app/views/issues/_form.html.erb (28.3ms)
  Rendered attachments/_form.html.erb (1.0ms)
  Rendered issues/_edit.html.erb (34.4ms)
  Rendered issues/_action_menu_edit.html.erb (36.7ms)
Deface: 'force history always' matched 0 times with '#history'
Deface: 'add quick notes' matched 0 times with '#history'
Deface: [WARNING] No :original defined for 'force history always', you should change its definition to include:
 :original => '617f5af73d71460b479003b50be8782d03899f17' 
Deface: [WARNING] No :original defined for 'force history always', you should change its definition to include:
 :original => '405d8bfa852a5a24038a6f7461470ff73f9faf9d' 
Deface: [WARNING] No :original defined for 'force history always', you should change its definition to include:
 :original => '617f5af73d71460b479003b50be8782d03899f17' 
Deface: [WARNING] No :original defined for 'add quick notes', you should change its definition to include:
 :original => '0df44d86535814629215cef053b5a77e92cdac2b' 
Deface: [WARNING] No :original defined for 'add quick notes', you should change its definition to include:
 :original => '0df44d86535814629215cef053b5a77e92cdac2b' 
Deface: [WARNING] No :original defined for 'add quick notes', you should change its definition to include:
 :original => '0df44d86535814629215cef053b5a77e92cdac2b' 
  Rendered plugins/mega_calendar/app/views/issues/show.html.erb (135.4ms)
  Rendered plugins/redmine_rt/app/views/issues/show.html.erb within layouts/base (136.1ms)
Completed 500 Internal Server Error in 182ms (ActiveRecord: 21.5ms)
  
ActionView::Template::Error (undefined local variable or method `issue_history_tabs_for_redmine_rt' for #<#<Class:0x000055d7d9b8bcd8>:0x00007f59b6db72b8>
Did you mean?  issue_history_tabs):
    220: 
    221: " %>
    222: <div id="history" data-comment_sorting="<%= User.current.wants_comments_in_reverse_order? ? 'desc' : 'asc' %>">
    223: <%= render_tabs issue_history_tabs_for_redmine_rt, issue_history_default_tab %>
    224: </div>
    225: <% end %>
    226: 
  
plugins/mega_calendar/app/views/issues/show.html.erb:223:in `_fcfd76d042c24f91b045b12c9ac5ba9a'
plugins/redmine_rt/app/views/issues/show.html.erb:16:in `_3987206f4ab5db21043ca5080be4d66e'
app/controllers/issues_controller.rb:112:in `block (2 levels) in show'
app/controllers/issues_controller.rb:104:in `show'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by leoniscsem** [comment] 2021-12-29 10:19
I am testing the plugin with various other popular plugins installed. I will post compatibility issues here:

* [RedmineUp Tags](https://www.redmine.org/plugins/redmineup_tags)
* [RedmineUp Zenedit](https://www.redmine.org/plugins/redmine_zenedit)

**Comment by MayamaTakeshi** [comment] 2021-12-29 23:44
Thanks for reporting.
Regarding mega_calendar, I tested and confirmed the issue.
I googled and I believe the problem is similar to this:
  https://github.com/ixti/redmine_tags/issues/45

Following the links I eventually reached this:
  https://github.com/ande3577/redmine-graphs-plugin/issues/12
where it is said that some plugins would replace the original helper modules with their own version.
I have not checked the code of mega_calendar yet but it seems it does this as the issue_history_tabs_for_redmine_rt is a method I am adding to the original IssuesHelper module and if it is not being found one possibility is that the module was replaced.
If confirmed, this might get complicated to solve (the proposed solution is a hack) and I might need to talk with the other plugins devs to get a clean solution.
Anyway, I don't have much time to work on this right now so a solution (even a hackish one) might not come soon.

**Comment by MayamaTakeshi** [comment] 2021-12-30 05:32
Hi,
I got some time to work on this. 
I confirmed the problem also happens with "RedmineUp Tags" but not with "RedmineUp Zenedit".
Investigation showed the issue is not the same as I mentioned before.
I am not sure yet why the problem happens but I changed how I patch the redmine code and now the error doesn't happen anymore. Please fetch the latest changes.
There might be other conflicts with these plugins but at least for now the issues page works with all the 3 plugins you mentioned.

**Comment by leoniscsem** [comment] 2021-12-30 13:13
If you don't mind, I would like to ask you to keep this issue open. We use Redmine with an extensive list of plugins, so we are a good "testing ground", thus I would continue reporting compatibility issues with the respective errors thrown. It might help others, who face issues with compatibility.

**Comment by MayamaTakeshi** [comment] 2021-12-30 21:59
OK. No problem.

**Comment by leoniscsem** [comment] 2022-01-02 03:13
Thank you for keeping this open. This time I wanted to report back about a plugin you maybe would like to recommend on your redmine.org plugin page, because it enhances the features of your plugin in a great way: [Ajax Redmine Issue Dynamic Edit](https://www.redmine.org/plugins/redmine_issue_dynamic_edit)

I have tested it thoroughly and it works flawlessly together with yours. I found a few issues in the logs, but they are not critical. Of course I do not know if this is of relevance for you too, but given the fact that you invested a lot of time to create your plugin, I think you had a "design concept" for enhanced Redmine functionality in mind.

**Comment by MayamaTakeshi** [comment] 2022-01-02 05:30
Thanks. I have added a mention to redmine_issue_dynamic_edit in my plugin page: https://www.redmine.org/plugins/redmine_rt
For completeness I have opened #7.

Regarding my plugin actually I wrote it mostly to get some experience with rails.
Also, my employer integrates pbx solutions with HelpDesk/CRM platforms like Zendesk and I was hoping we could offer hosted Redmine/redmine_rt to be a cheaper alternative but I could not get my company interested in this.

Regarding a "design concept", I planned the plugin to be more of a showcase of what could be done.
My idea was that redmine devs/users would get interested in real time features and then we could move the code to be part of the redmine core so that any page created either by the core or by plugins (and not just the issues page) could be automatically updated and each plugin augmenting views would use the same subscription mechanism to be notified of changes and update the elements it added to the view.

**Comment by leoniscsem** [comment] 2022-01-02 13:30
That background story is amazing! The plugin is of very high quality in my opinion and sports a rather complex approach, so "just to see what I can do with Rails" is remarkable. I actually have a few questions for you, would you care having conversation on Gitter? My timezone is -1 hour of yours, you could ping me there anytime.

**Comment by MayamaTakeshi** [comment] 2022-01-02 23:42
Actually the implementation is very simple. I have not spent a lot of time with this and most of it was actually used studying rails/redmine plugin architecture and reading/testing other devs plugins to understand how to implement mine.
I realized this: if converting the existing redmine code to a full real-time SPA style app were simple, the core devs would have done it already to appeal to new users that are used to real-time features.
Not having this and in need of an alternative to expensive HelpDesk/CRM services, I thought I could add real-time features to existing redmine pages just by having a communication channel that would be used by a small amount of client javascript code in each page where real-time updates were of relevance. 
Aside from that, the websocket allows to implement any other real-time features like chat, dashboards, notifications of events (like incoming customers calls, in case of pbx integration) etc.

I'm busy right now, but I will contact you later on Gitter.

**Comment by leoniscsem** [comment] 2022-01-03 01:09
> Aside from that, the websocket allows to implement any other real-time features like chat, dashboards, notifications of events (like incoming customers calls, in case of pbx integration) etc.

This is exactly what I was referring to in my comment about the complex nature in the architecture of the plugin - a solution via websocket just offers many more possibilities. I have sent you an email, we can talk on Gitter later.

**Comment by MayamaTakeshi** [comment] 2023-04-30 21:35
Hi @leoniscsem.
I hope you are well.
I've been working on some plugin conflicts recently and it will be better to have separate tickets for each of them. 
So I'm closing this one. Please report any new issues on individual tickets. Thanks.

**Closed as completed by MayamaTakeshi** 2023-04-30 21:35 UTC
